package com.transaction.service.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@NoArgsConstructor
@AllArgsConstructor
@Data
@Entity
@Table(name = "transactions")
public class Transaction {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(name = "transaction_Id", nullable = false, unique = true)
    private String transactionId;

    @Column(nullable = false)
    private String senderUpiId;

    @Column(nullable = false)
    private Integer senderProfileId;  // Profile ID from user-service

    @Column(nullable = false)
    private String receiverUpiId;

    @Column(nullable = false)
    private Integer receiverProfileId;  // Profile ID from user-service

    @Column(nullable = false)
    private BigDecimal amount;

    @Column(nullable = false)
    private String status;  // "PENDING", "SUCCESS", "FAILED"

    @Column(length = 25)
    private String paymentMethod;  // UPI, Bluetooth , Card ,etc

    @Column(length = 25)
    private String source; // REGULAR, BLE_SYNC, etc

    @Column(nullable = false)
    private String txnHash;  // SHA-256 hash of transaction data

    @Column(nullable = false)
    private LocalDateTime expireAt;  // if transaction not processed by this time, transaction fails

    @Column(length = 500)
    private String Description;

    @Column(name = "created_At", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_At", nullable = false)
    private LocalDateTime updatedAt;

  // ===== BLE-SPECIFIC FIELDS =====

    @Column(columnDefinition = "LONGTEXT")
    private String encryptedPayload;  // Base64 encrypted payment data

    @Column(length = 128)
    private String signature;  // SHA-256 hex signature of payload

    @Column(length = 50)
    private String nonce;  // Random nonce for replay attack prevention

    @Column(name = "is_offline")
    private Boolean isOffline;   // true for BLE payments, false for regular

    @Column(name = "received_at")
    private LocalDateTime receivedAt;  // When payment was received on phone

    @Column(name = "synced_at")
    private LocalDateTime syncedAt;  // When synced to backend

    @Column(length = 100)
    private String backendTransactionId;  // UUID generated by backend

    @Column(name = "sync_attempts")
    private Integer syncAttempts = 0;  // Number of sync attempts

    @Column(columnDefinition = "LONGTEXT")
    private String lastSyncError;  // Last error message from sync attempt

    @Column(name = "payload_version")
    private Integer payloadVersion = 1;   // BLE payload format version

    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }
}
